### PR TITLE
Added Dockerfile and updated readme

### PR DESCRIPTION
**Pull request by wjbeckett**
I have added a dockerfile for those that wish to run this in docker. Currently the docker-compose example is pointing at my docker hub but this can be updated to yours if you like.

I have been testing this docker image and it works flawlessly.

I have also updated the readme with some Docker and Home-Assistant info.

### CODE REVIEW

**Comment by wjbeckett** [comment]
The Docker implementation probably could be refined. But it works.

**Comment by liaan** [comment]
@wjbeckett 

I will check this out, I have 0 knowledge of docker.   Its not something I ever needed to learn.

will add to todo list

**Comment by wjbeckett** [comment]
No Problem @liaan . 
I only run Docker containers on my host so this was a huge step froward for me. 
It works in the current iteration and will pull down the latest commit when the container is updated.

Only caveat (not really a caveat, more of a note) is that `networking_mode: host` must be set in the container config so that monitor.py can attach to the local LAN to discover AC units.

**Comment by liaan** [comment]
Cool .. will definitley check.  I run openvz / vm / LXC at home/production.. So . what is ANOTHER container system  to learn ;-)    . I see homeassist uses it a lot, so probably good idea

**Comment by wjbeckett** [comment]
> Cool .. will definitley check. I run openvz / vm / LXC at home/production.. So . what is ANOTHER container system to learn ;-) . I see homeassist uses it a lot, so probably good idea

It's not too bad actually. Learning curve isn't too steep. I can maintain the Docker image if you like going forward (published under your repo, I'll just be the maintainer).

**Comment by liaan** [comment]
@wjbeckett 

See you keeping busy .. I'm just doing the last bit of changes (auto MQTT discovery) then most of the work should be done , then hopefully one can start working on fixing the bugs...

**Comment by wjbeckett** [comment]
@liaan Oh nice! 
Do you mean auto discovery into Home-assistant? Or just MQTT discovery from within the LAN back to the monitor.py. 

I'm just keeping this up to date so I can test the docker image as you add things. So far so good :-)

**Comment by liaan** [comment]
@wjbeckett 

Auto discovery in HA using MQTT autodisocvery (.   You just need to enable the option in HA (I updated the readme) (https://www.home-assistant.io/docs/mqtt/discovery/)

I made changes to the topics to make HA and Homekit work on same script (conflict in naming). so just check if you have your aircon manually configured

**Comment by wjbeckett** [comment]
Holy crap! That's amazing @liaan!
I'll update the docker image and test. 

Ooh, need to update your sample_config file with the new and correct values. My docker build copies that file to create a base config.yml (because the app doesn't start without it).

**Comment by wjbeckett** [comment]
@liaan, also need to look at the fan modes and how they translate to Home-Assistant, if you haven't already. 

From what I can tell, there is no strict list for fan_modes like there is with modes. So you could potentially utilise all of the AC functions (auto, mute, low, mid, high, turbo)

**Comment by liaan** [comment]
> @liaan, also need to look at the fan modes and how they translate to Home-Assistant, if you haven't already.
> From what I can tell, there is no strict list for fan_modes like there is with modes. So you could potentially utilise all of the AC functions (auto, mute, low, mid, high, turbo)

See now read docs wrong.. I will update at some point.   I want to see how this Docker things work now, otherwise one might do a seperate repo for the docker and just do a pull of the files in here to otherone somehow

**Comment by wjbeckett** [comment]
just had a thought about this - let's forget this merge request. 
I'll just maintain the docker image separately. that way we won't have to worry about this merge at all and you won't have to worry about having to maintain a docker image as well - I can do that for you.

Thoughts @liaan ?

**Comment by liaan** [comment]
Created dedicated repo for this: 

https://github.com/liaan/broadlink_ac_mqtt_docker

**Pull request closed without merging**
