### PR TITLE
Retain config and some code cleanup

### PR DESCRIPTION
**Pull request by mrekin**
1. Added "retain" config option. Usefull for home assistant autodiscovery (with ratain==false hass don't get autodiscovery message in some cases and need to restart broadling_ac_mqtt to send it again)
2. Debug messages, readme, config_sample cleanup\update

### CODE REVIEW

**Comment by liaan** [comment]
@mrekin  .Thanks for this!! .. (you can see this was coded as hack job originally) :)

Just one thing, can you amend the config to say mqtt_topic_retain  rather than just topic (or something more explanatory), people might think it retains in HA or something

**Comment by mrekin** [comment]
You are right, I'll update config parameter name. But i'm not clear how to update it in pull request need to find this option.. :)

**Comment by liaan** [comment]
> You are right, I'll update config parameter name. But i'm not clear how to update it in pull request need to find this option.. :)

don't ask me .. i've only started using github properly month ago

**Comment by liaan** [comment]
I'll merge this one, then just do new one again

**Pull request merged**
