### PR TITLE
Ambient temperature accuracy

### LINKED ISSUE #53: AC ambient temperature
Probably, I found the ambient temperature value after the decimal point
It is not byte offset, and value is on 33 byte. I'll check in AC Freedom app and temp is equal
[34, 0, 187, 0, 7, 0, 0, 0, 24, 0, 1, 33, 224, 129, 0, 7, 125, 57, 81, 81, 81, 100, 41, 40, 87, 57, 60, 16, 174, 240, 0, 0, 0, **8**, 184, 251, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

### LINKED ISSUE #54: No ambient temperature value
Sometimes I get an ambient temperature value of 0.
Normal log with ambient temperature:
```
2020-09-28 12:41:58,082,82 DEBUG    [ac_db.py:548] Acinfo Raw Response: 00100010 00000000 10111011 00000000 00000111 00000000 00000000 00000000 00011000 00000000 00000001 00100001 11100000 00100000 00000000 00000000 00000000 00111000 00110011 00110011 00110011 01100100 00101011 00101011 00101011 00111001 00000000 00000000 10010010 00011000 00000000 00000000 00000000 00000001 11110101 01101111 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
2020-09-28 12:41:58,083,83 DEBUG    [ac_db.py:549] Acinfo Raw Hex: 22 00 bb 00 07 00 00 00 18 00 01 21 e0 20 00 00 00 38 33 33 33 64 2b 2b 2b 39 00 00 92 18 00 00 00 01 f5 6f 00 00 00 00 00 00 00 00 00 00 00 00
2020-09-28 12:41:58,083,83 DEBUG    [ac_db.py:553] AcInfo: 00100001 11100000 00100000 00000000 00000000 00000000 00111000 00110011 00110011 00110011 01100100 00101011 00101011 00101011 00111001 00000000 00000000 10010010 00011000 00000000 00000000 00000000 00000001 11110101 01101111 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
2020-09-28 12:41:58,084,84 DEBUG    [ac_db.py:596] 00000000 00000001 00010001 01110111 00110000 00010111 01000000 00000000 00100000 00000000 00000000 00000000 00000000 00010000 00000000 00000000 10001111 01011101 00110001 11111010 10010001 11010100 00011111
2020-09-28 12:41:58,084,84 DEBUG    [ac_db.py:600] bb 00 07 00 00 00 0f 00 01 11 77 30 17 40 00 20 00 00 00 00 10 00 00 8f 5d 31 fa 91 d4 1f
2020-09-28 12:41:58,084,84 DEBUG    [AcToMqtt.py:213] Force update is: True
2020-09-28 12:41:58,085,85 DEBUG    [AcToMqtt.py:253] publishing on topic "aircon/34ea34ddaaea/temp/value", data "22.0"
2020-09-28 12:41:58,085,85 DEBUG    [AcToMqtt.py:253] publishing on topic "aircon/34ea34ddaaea/ambient_temp/value", data "24"
2020-09-28 12:41:58,085,85 DEBUG    [AcToMqtt.py:253] publishing on topic "aircon/34ea34ddaaea/power/value", data "OFF"
2020-09-28 12:41:58,086,86 DEBUG    [AcToMqtt.py:253] publishing on topic "aircon/34ea34ddaaea/fixation_v/value", data "AUTO"
2020-09-28 12:41:58,086,86 DEBUG    [AcToMqtt.py:253] publishing on topic "aircon/34ea34ddaaea/mode/value", data "COOLING"
2020-09-28 12:41:58,086,86 DEBUG    [AcToMqtt.py:253] publishing on topic "aircon/34ea34ddaaea/sleep/value", data "OFF"
2020-09-28 12:41:58,086,86 DEBUG    [AcToMqtt.py:253] publishing on topic "aircon/34ea34ddaaea/display/value", data "ON"
2020-09-28 12:41:58,087,87 DEBUG    [AcToMqtt.py:253] publishing on topic "aircon/34ea34ddaaea/mildew/value", data "OFF"
2020-09-28 12:41:58,087,87 DEBUG    [AcToMqtt.py:253] publishing on topic "aircon/34ea34ddaaea/health/value", data "OFF"
2020-09-28 12:41:58,087,87 DEBUG    [AcToMqtt.py:253] publishing on topic "aircon/34ea34ddaaea/fixation_h/value", data "AUTO"
2020-09-28 12:41:58,087,87 DEBUG    [AcToMqtt.py:253] publishing on topic "aircon/34ea34ddaaea/ifeel/value", data "OFF"
2020-09-28 12:41:58,088,88 DEBUG    [AcToMqtt.py:253] publishing on topic "aircon/34ea34ddaaea/mute/value", data "OFF"
2020-09-28 12:41:58,088,88 DEBUG    [AcToMqtt.py:253] publishing on topic "aircon/34ea34ddaaea/turbo/value", data "OFF"
2020-09-28 12:41:58,088,88 DEBUG    [AcToMqtt.py:253] publishing on topic "aircon/34ea34ddaaea/clean/value", data "OFF"
2020-09-28 12:41:58,088,88 DEBUG    [AcToMqtt.py:253] publishing on topic "aircon/34ea34ddaaea/macaddress/value", data "34ea34ddaaea"
2020-09-28 12:41:58,088,88 DEBUG    [AcToMqtt.py:253] publishing on topic "aircon/34ea34ddaaea/device_name/value", data "None"
2020-09-28 12:41:58,089,89 DEBUG    [AcToMqtt.py:253] publishing on topic "aircon/34ea34ddaaea/mode_homekit/value", data "Off"
2020-09-28 12:41:58,089,89 DEBUG    [AcToMqtt.py:253] publishing on topic "aircon/34ea34ddaaea/mode_homeassistant/value", data "off"
2020-09-28 12:41:58,089,89 DEBUG    [AcToMqtt.py:253] publishing on topic "aircon/34ea34ddaaea/fanspeed/value", data "MEDIUM"
2020-09-28 12:41:58,090,90 DEBUG    [AcToMqtt.py:253] publishing on topic "aircon/34ea34ddaaea/fanspeed_homeassistant/value", data "Medium"
```

Log without ambient temperature value:
```
2020-09-28 12:42:18,217,217 DEBUG    [ac_db.py:548] Acinfo Raw Response: 00100010 00000000 10111011 00000000 00000111 00000000 00000000 00000000 00011000 00000000 00000001 001000
01 11100000 00100000 00000000 00000000 00000000 00111000 00110011 00110011 00110011 01100100 00101011 00101011 00101011 00111001 00000000 00000000 10010010 00011000 00000000 0000
0000 00000000 00000001 11110101 01101111 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
2020-09-28 12:42:18,217,217 DEBUG    [ac_db.py:549] Acinfo Raw Hex: 22 00 bb 00 07 00 00 00 18 00 01 21 e0 20 00 00 00 38 33 33 33 64 2b 2b 2b 39 00 00 92 18 00 00 00 01 f5 6f 00
 00 00 00 00 00 00 00 00 00 00 00
2020-09-28 12:42:18,217,217 DEBUG    [ac_db.py:553] AcInfo: 00100001 11100000 00100000 00000000 00000000 00000000 00111000 00110011 00110011 00110011 01100100 00101011 00101011 0
0101011 00111001 00000000 00000000 10010010 00011000 00000000 00000000 00000000 00000001 11110101 01101111 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
 00000000 00000000 00000000 00000000
2020-09-28 12:42:18,218,218 DEBUG    [AcToMqtt.py:109] No status
2020-09-28 12:42:18,218,218 DEBUG    [ac_db.py:548] Acinfo Raw Response: 00011001 00000000 10111011 00000000 00000111 00000000 00000000 00000000 00001111 00000000 00000001 000100
01 01110111 00110000 00010111 01000000 00000000 00100000 00000000 00000000 00000000 00000000 00010000 00000000 00000000 10001111 01011101 00110001 11111010 10010001 11010100 0001
1111
2020-09-28 12:42:18,218,218 DEBUG    [ac_db.py:549] Acinfo Raw Hex: 19 00 bb 00 07 00 00 00 0f 00 01 11 77 30 17 40 00 20 00 00 00 00 10 00 00 8f 5d 31 fa 91 d4 1f
2020-09-28 12:42:18,218,218 DEBUG    [ac_db.py:553] AcInfo: 00010001 01110111 00110000 00010111 01000000 00000000 00100000 00000000 00000000 00000000 00000000 00010000 00000000 0
0000000 10001111 01011101 00110001 11111010 10010001 11010100 00011111
2020-09-28 12:42:18,218,218 DEBUG    [AcToMqtt.py:109] No status
2020-09-28 12:42:18,218,218 DEBUG    [ac_db.py:548] Acinfo Raw Response: 00011001 00000000 10111011 00000000 00000111 00000000 00000000 00000000 00001111 00000000 00000001 000100
01 01110111 00110000 00011000 01000000 00000000 00100000 00000000 00000000 00000000 00000000 00010000 00000000 00000000 10001110 01011101 00110001 11111010 10010001 11010100 0001
1111
2020-09-28 12:42:18,219,219 DEBUG    [ac_db.py:549] Acinfo Raw Hex: 19 00 bb 00 07 00 00 00 0f 00 01 11 77 30 18 40 00 20 00 00 00 00 10 00 00 8e 5d 31 fa 91 d4 1f
2020-09-28 12:42:18,219,219 DEBUG    [ac_db.py:553] AcInfo: 00010001 01110111 00110000 00011000 01000000 00000000 00100000 00000000 00000000 00000000 00000000 00010000 00000000 0
0000000 10001110 01011101 00110001 11111010 10010001 11010100 00011111
2020-09-28 12:42:18,499,499 DEBUG    [AcToMqtt.py:109] No status
2020-09-28 12:42:18,826,826 DEBUG    [ac_db.py:548] Acinfo Raw Response: 00011001 00000000 10111011 00000000 00000111 00000000 00000000 00000000 00001111 00000000 00000001 000100
01 01110111 00110000 00011000 01000000 00000000 00100000 00000000 00000000 00000000 00000000 00010000 00000000 00000000 10001110 01011101 00110001 11111010 10010001 11010100 0001
1111
2020-09-28 12:42:18,827,827 DEBUG    [ac_db.py:549] Acinfo Raw Hex: 19 00 bb 00 07 00 00 00 0f 00 01 11 77 30 18 40 00 20 00 00 00 00 10 00 00 8e 5d 31 fa 91 d4 1f
2020-09-28 12:42:18,827,827 DEBUG    [ac_db.py:553] AcInfo: 00010001 01110111 00110000 00011000 01000000 00000000 00100000 00000000 00000000 00000000 00000000 00010000 00000000 0
0000000 10001110 01011101 00110001 11111010 10010001 11010100 00011111
2020-09-28 12:42:19,069,69 DEBUG    [AcToMqtt.py:109] No status
2020-09-28 12:42:19,335,335 DEBUG    [ac_db.py:548] Acinfo Raw Response: 00011001 00000000 10111011 00000000 00000111 00000000 00000000 00000000 00001111 00000000 00000001 000100
01 01110111 00110000 00011000 01000000 00000000 00100000 00000000 00000000 00000000 00000000 00010000 00000000 00000000 10001110 01011101 00110001 11111010 10010001 11010100 0001
1111
2020-09-28 12:42:19,335,335 DEBUG    [ac_db.py:549] Acinfo Raw Hex: 19 00 bb 00 07 00 00 00 0f 00 01 11 77 30 18 40 00 20 00 00 00 00 10 00 00 8e 5d 31 fa 91 d4 1f
2020-09-28 12:42:19,336,336 DEBUG    [ac_db.py:553] AcInfo: 00010001 01110111 00110000 00011000 01000000 00000000 00100000 00000000 00000000 00000000 00000000 00010000 00000000 00000000 10001110 01011101 00110001 11111010 10010001 11010100 00011111
2020-09-28 12:42:19,628,628 DEBUG    [AcToMqtt.py:109] No status
2020-09-28 12:42:19,865,865 DEBUG    [ac_db.py:548] Acinfo Raw Response: 00011001 00000000 10111011 00000000 00000111 00000000 00000000 00000000 00001111 00000000 00000001 00010001 01110111 00110000 00011000 01000000 00000000 00100000 00000000 00000000 00000000 00000000 00010000 00000000 00000000 10001110 01011101 00110001 11111010 10010001 11010100 00011111
2020-09-28 12:42:19,865,865 DEBUG    [ac_db.py:549] Acinfo Raw Hex: 19 00 bb 00 07 00 00 00 0f 00 01 11 77 30 18 40 00 20 00 00 00 00 10 00 00 8e 5d 31 fa 91 d4 1f
2020-09-28 12:42:19,866,866 DEBUG    [ac_db.py:553] AcInfo: 00010001 01110111 00110000 00011000 01000000 00000000 00100000 00000000 00000000 00000000 00000000 00010000 00000000 00000000 10001110 01011101 00110001 11111010 10010001 11010100 00011111
2020-09-28 12:42:20,261,261 DEBUG    [AcToMqtt.py:109] No status
2020-09-28 12:42:20,483,483 DEBUG    [ac_db.py:548] Acinfo Raw Response: 00011001 00000000 10111011 00000000 00000111 00000000 00000000 00000000 00001111 00000000 00000001 00010001 01110111 00110000 00011000 01000000 00000000 00100000 00000000 00000000 00000000 00000000 00010000 00000000 00000000 10001110 01011101 00110001 11111010 10010001 11010100 00011111
2020-09-28 12:42:20,484,484 DEBUG    [ac_db.py:549] Acinfo Raw Hex: 19 00 bb 00 07 00 00 00 0f 00 01 11 77 30 18 40 00 20 00 00 00 00 10 00 00 8e 5d 31 fa 91 d4 1f
2020-09-28 12:42:20,484,484 DEBUG    [ac_db.py:553] AcInfo: 00010001 01110111 00110000 00011000 01000000 00000000 00100000 00000000 00000000 00000000 00000000 00010000 00000000 00000000 10001110 01011101 00110001 11111010 10010001 11010100 00011111
2020-09-28 12:42:20,876,876 DEBUG    [AcToMqtt.py:109] No status
2020-09-28 12:42:21,077,77 DEBUG    [ac_db.py:548] Acinfo Raw Response: 00011001 00000000 10111011 00000000 00000111 00000000 00000000 00000000 00001111 00000000 00000001 00010001 01110111 00110000 00011000 01000000 00000000 00100000 00000000 00000000 00000000 00000000 00010000 00000000 00000000 10001110 01011101 00000000 00000000 00000000 00000000 00000000
2020-09-28 12:42:21,078,78 DEBUG    [ac_db.py:549] Acinfo Raw Hex: 19 00 bb 00 07 00 00 00 0f 00 01 11 77 30 18 40 00 20 00 00 00 00 10 00 00 8e 5d 00 00 00 00 00
2020-09-28 12:42:21,078,78 DEBUG    [ac_db.py:553] AcInfo: 00010001 01110111 00110000 00011000 01000000 00000000 00100000 00000000 00000000 00000000 00000000 00010000 00000000 00000000 10001110 01011101 00000000 00000000 00000000 00000000 00000000
2020-09-28 12:42:21,394,394 DEBUG    [AcToMqtt.py:109] No status
2020-09-28 12:42:21,659,659 DEBUG    [ac_db.py:548] Acinfo Raw Response: 00011001 00000000 10111011 00000000 00000111 00000000 00000000 00000000 00001111 00000000 00000001 00010001 01110111 00110000 00011000 01000000 00000000 00100000 00000000 00000000 00000000 00000000 00010000 00000000 00000000 10001110 01011101 00110001 11111010 10010001 11010100 00011111
2020-09-28 12:42:21,659,659 DEBUG    [ac_db.py:549] Acinfo Raw Hex: 19 00 bb 00 07 00 00 00 0f 00 01 11 77 30 18 40 00 20 00 00 00 00 10 00 00 8e 5d 31 fa 91 d4 1f
2020-09-28 12:42:21,660,660 DEBUG    [ac_db.py:553] AcInfo: 00010001 01110111 00110000 00011000 01000000 00000000 00100000 00000000 00000000 00000000 00000000 00010000 00000000 00000000 10001110 01011101 00110001 11111010 10010001 11010100 00011111
2020-09-28 12:42:22,041,41 DEBUG    [AcToMqtt.py:109] No status
2020-09-28 12:42:22,298,298 DEBUG    [ac_db.py:548] Acinfo Raw Response: 00011001 00000000 10111011 00000000 00000111 00000000 00000000 00000000 00001111 00000000 00000001 00010001 01110111 00110000 00011000 01000000 00000000 00100000 00000000 00000000 00000000 00000000 00010000 00000000 00000000 10001110 01011101 00000000 00000000 00000000 00000000 00000000
2020-09-28 12:42:22,298,298 DEBUG    [ac_db.py:549] Acinfo Raw Hex: 19 00 bb 00 07 00 00 00 0f 00 01 11 77 30 18 40 00 20 00 00 00 00 10 00 00 8e 5d 00 00 00 00 00
2020-09-28 12:42:22,298,298 DEBUG    [ac_db.py:553] AcInfo: 00010001 01110111 00110000 00011000 01000000 00000000 00100000 00000000 00000000 00000000 00000000 00010000 00000000 00000000 10001110 01011101 00000000 00000000 00000000 00000000 00000000
2020-09-28 12:42:22,615,615 DEBUG    [ac_db.py:596] 00000000 00000001 00010001 01110111 00110000 00011000 01000000 00000000 00100000 00000000 00000000 00000000 00000000 00010000 00000000 00000000 10001110 01011101 10110010 10011000 00110101 00011111 10110101
2020-09-28 12:42:22,616,616 DEBUG    [ac_db.py:600] bb 00 07 00 00 00 0f 00 01 11 77 30 18 40 00 20 00 00 00 00 10 00 00 8e 5d b2 98 35 1f b5
2020-09-28 12:42:22,616,616 DEBUG    [AcToMqtt.py:213] Force update is: True
2020-09-28 12:42:22,616,616 DEBUG    [AcToMqtt.py:253] publishing on topic "aircon/34ea34ddaaea/temp/value", data "22.0"
2020-09-28 12:42:22,616,616 DEBUG    [AcToMqtt.py:253] publishing on topic "aircon/34ea34ddaaea/ambient_temp/value", data "0"
2020-09-28 12:42:22,617,617 DEBUG    [AcToMqtt.py:253] publishing on topic "aircon/34ea34ddaaea/power/value", data "OFF"
2020-09-28 12:42:22,617,617 DEBUG    [AcToMqtt.py:253] publishing on topic "aircon/34ea34ddaaea/fixation_v/value", data "AUTO"
2020-09-28 12:42:22,617,617 DEBUG    [AcToMqtt.py:253] publishing on topic "aircon/34ea34ddaaea/mode/value", data "COOLING"
2020-09-28 12:42:22,618,618 DEBUG    [AcToMqtt.py:253] publishing on topic "aircon/34ea34ddaaea/sleep/value", data "OFF"
2020-09-28 12:42:22,618,618 DEBUG    [AcToMqtt.py:253] publishing on topic "aircon/34ea34ddaaea/display/value", data "ON"
2020-09-28 12:42:22,618,618 DEBUG    [AcToMqtt.py:253] publishing on topic "aircon/34ea34ddaaea/mildew/value", data "OFF"
2020-09-28 12:42:22,618,618 DEBUG    [AcToMqtt.py:253] publishing on topic "aircon/34ea34ddaaea/health/value", data "OFF"
2020-09-28 12:42:22,619,619 DEBUG    [AcToMqtt.py:253] publishing on topic "aircon/34ea34ddaaea/fixation_h/value", data "AUTO"
2020-09-28 12:42:22,619,619 DEBUG    [AcToMqtt.py:253] publishing on topic "aircon/34ea34ddaaea/ifeel/value", data "OFF"
2020-09-28 12:42:22,620,620 DEBUG    [AcToMqtt.py:253] publishing on topic "aircon/34ea34ddaaea/mute/value", data "OFF"
2020-09-28 12:42:22,620,620 DEBUG    [AcToMqtt.py:253] publishing on topic "aircon/34ea34ddaaea/turbo/value", data "OFF"
2020-09-28 12:42:22,620,620 DEBUG    [AcToMqtt.py:253] publishing on topic "aircon/34ea34ddaaea/clean/value", data "OFF"
2020-09-28 12:42:22,621,621 DEBUG    [AcToMqtt.py:253] publishing on topic "aircon/34ea34ddaaea/macaddress/value", data "34ea34ddaaea"
2020-09-28 12:42:22,621,621 DEBUG    [AcToMqtt.py:253] publishing on topic "aircon/34ea34ddaaea/device_name/value", data "None"
2020-09-28 12:42:22,621,621 DEBUG    [AcToMqtt.py:253] publishing on topic "aircon/34ea34ddaaea/mode_homekit/value", data "Off"
2020-09-28 12:42:22,622,622 DEBUG    [AcToMqtt.py:253] publishing on topic "aircon/34ea34ddaaea/mode_homeassistant/value", data "off"
2020-09-28 12:42:22,622,622 DEBUG    [AcToMqtt.py:253] publishing on topic "aircon/34ea34ddaaea/fanspeed/value", data "MEDIUM"
2020-09-28 12:42:22,622,622 DEBUG    [AcToMqtt.py:253] publishing on topic "aircon/34ea34ddaaea/fanspeed_homeassistant/value", data "Medium"
```

Difference:
```
# OK
22 00 bb 00 07 00 00 00 18 00 01 21 e0 20 00 00 00 38 33 33 33 64 2b 2b 2b 39 00 00 92 18 00 00 00 01 f5 6f 00 00 00 00 00 00 00 00 00 00 00 00
# No status
19 00 bb 00 07 00 00 00 0f 00 01 11 77 30 18 40 00 20 00 00 00 00 10 00 00 8e 5d 31 fa 91 d4 1f
# No temperature
19 00 bb 00 07 00 00 00 0f 00 01 11 77 30 18 40 00 20 00 00 00 00 10 00 00 8e 5d 00 00 00 00 00
```

### PR DESCRIPTION
**Pull request by Anonym-tsk**
Fix #53
And maybe fix #54
+ Small refactoring

### CODE REVIEW

**Comment by liaan** [comment]
As per other pull request, to many changes to figure out what have changed.  This one shows 1546 changes.  Can you give me the few lines of code you changes so I can check please.

**Comment by Anonym-tsk** [comment]
Sorry for so many changes, but my IDE doesn't want to save file without refactoring. A lot of line-ending tabs, mix of tabs and spaces, unused code and more.
Please look at pull request with this option
image

**Comment by liaan** [comment]
so its just line 546 that changed?

I use visual studio code to code, and its not complaining .....   The formatting issues is from hacking together to many pieces of code over the years and I just fixed it till github cleared the formatting checking rules. ;-)

**Comment by Anonym-tsk** [comment]
Removed refactoring here too

**Comment by liaan** [comment]
Busy testing this and don't work on my aircons.

I will ask some other to test this and see if only some AC's do ambient in decimals

**Comment by liaan** [comment]
Merging this manually, closeing

**Pull request closed without merging**
