### PR TITLE
Feature/log to mqtt

### PR DESCRIPTION
**Pull request by wayne-love**
Copies log message to MQTT topic <base>/log for easier monitoring and debugging.

### CODE REVIEW

**Comment by liaan** [comment]
Just had very quick look..   is there any error checking if mqtt is down?  Ie, mqtt down, then print to cmd line or log file?

________________________________

**Comment by wayne-love** [comment]
No, nothing specific other than the generic network error.  Can wrap it up
in a try catch if you like. Made the assumption that the MQTT server was
always available.

**Comment by liaan** [comment]
Had issue before where users enter mqtt settings wrong..  cannot actually remember what current code does, think just prints to console if unable to connect...  (Dont have access to source now)

________________________________

**Comment by wayne-love** [comment]
At the moment the message is the os one ... “the machine refused
connection”.  Let me have a look in the morning and I’ll see if I can’t
make it nicer.

**Comment by wayne-love** [comment]
OK, so this commit is rubbish, it works but is no more than a hack please feel free to discard.  

What I should have done is added the addlistener after the mqtt connect in AcToMqtt.py and then a remove listener before the disconnect and tunneled all the communication through the existing mqtt session.  The problem is that the new listener will be a separate class to the the AcToMqtt class and therefore will not have access to the _publish method.

Happy to take suggestions for alternative implementations.

**Pull request closed without merging**
