### PR TITLE
Feature/win10 compatability

### PR DESCRIPTION
**Pull request by wayne-love**
Removed Linux specific signals to enable use on Win10, seems safe to do so as these have not explicit processing associated with them.  There may be a better way of doing this that I am not aware of.

### CODE REVIEW

**Comment by liaan** [comment]
I'll check if this works on my systems and merge if all seems ok

**Comment by wayne-love** [comment]
See Feb14 commit.  Have implemented a platform test, on Linux platforms no execution changes, on Windows platforms only Windows signals are captured.  Should be totally safe now.

**Comment by liaan** [comment]
Aa thanks

Will check out when office again..


________________________________

**Comment by liaan** [comment]
phewwwww ... not been on here in ages.

will try make plan to get this merged

**Pull request closed without merging**
